<?php

/**
 * BaseLeaveAccrualTimeSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country_code
 * @property integer $location_code
 * @property timestamp $scheduled_time
 * 
 * @method integer                  getId()             Returns the current record's "id" value
 * @method string                   getCountryCode()    Returns the current record's "country_code" value
 * @method integer                  getLocationCode()   Returns the current record's "location_code" value
 * @method timestamp                getScheduledTime()  Returns the current record's "scheduled_time" value
 * @method LeaveAccrualTimeSchedule setId()             Sets the current record's "id" value
 * @method LeaveAccrualTimeSchedule setCountryCode()    Sets the current record's "country_code" value
 * @method LeaveAccrualTimeSchedule setLocationCode()   Sets the current record's "location_code" value
 * @method LeaveAccrualTimeSchedule setScheduledTime()  Sets the current record's "scheduled_time" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveAccrualTimeSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_accrual_time_schedule');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('country_code', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('location_code', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('scheduled_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}