<?php

/**
 * BaseEmployeeLeaveAccrual
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $acc_id
 * @property string $leave_type_id
 * @property integer $employee_id
 * @property integer $leave_period_id
 * @property date $acc_time
 * @property decimal $acc_days
 * @property LeaveType $LeaveType
 * @property Employee $Employee
 * @property LeavePeriod $LeavePeriod
 * 
 * @method integer              getAccId()           Returns the current record's "acc_id" value
 * @method string               getLeaveTypeId()     Returns the current record's "leave_type_id" value
 * @method integer              getEmployeeId()      Returns the current record's "employee_id" value
 * @method integer              getLeavePeriodId()   Returns the current record's "leave_period_id" value
 * @method date                 getAccTime()         Returns the current record's "acc_time" value
 * @method decimal              getAccDays()         Returns the current record's "acc_days" value
 * @method LeaveType            getLeaveType()       Returns the current record's "LeaveType" value
 * @method Employee             getEmployee()        Returns the current record's "Employee" value
 * @method LeavePeriod          getLeavePeriod()     Returns the current record's "LeavePeriod" value
 * @method EmployeeLeaveAccrual setAccId()           Sets the current record's "acc_id" value
 * @method EmployeeLeaveAccrual setLeaveTypeId()     Sets the current record's "leave_type_id" value
 * @method EmployeeLeaveAccrual setEmployeeId()      Sets the current record's "employee_id" value
 * @method EmployeeLeaveAccrual setLeavePeriodId()   Sets the current record's "leave_period_id" value
 * @method EmployeeLeaveAccrual setAccTime()         Sets the current record's "acc_time" value
 * @method EmployeeLeaveAccrual setAccDays()         Sets the current record's "acc_days" value
 * @method EmployeeLeaveAccrual setLeaveType()       Sets the current record's "LeaveType" value
 * @method EmployeeLeaveAccrual setEmployee()        Sets the current record's "Employee" value
 * @method EmployeeLeaveAccrual setLeavePeriod()     Sets the current record's "LeavePeriod" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployeeLeaveAccrual extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_leave_accrual');
        $this->hasColumn('acc_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('leave_type_id', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             ));
        $this->hasColumn('employee_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('leave_period_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('acc_time', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('acc_days', 'decimal', 4, array(
             'type' => 'decimal',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LeaveType', array(
             'local' => 'leave_type_id',
             'foreign' => 'leaveTypeId'));

        $this->hasOne('Employee', array(
             'local' => 'employee_id',
             'foreign' => 'empNumber'));

        $this->hasOne('LeavePeriod', array(
             'local' => 'leave_period_id',
             'foreign' => 'leavePeriodId'));
    }
}