<?php

/**
 * BaseHolidayLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $holiday_id
 * @property integer $location_id
 * @property Holiday $Holiday
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getHolidayId()   Returns the current record's "holiday_id" value
 * @method integer         getLocationId()  Returns the current record's "location_id" value
 * @method Holiday         getHoliday()     Returns the current record's "Holiday" value
 * @method HolidayLocation setId()          Sets the current record's "id" value
 * @method HolidayLocation setHolidayId()   Sets the current record's "holiday_id" value
 * @method HolidayLocation setLocationId()  Sets the current record's "location_id" value
 * @method HolidayLocation setHoliday()     Sets the current record's "Holiday" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHolidayLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_holiday_location');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 10,
             ));
        $this->hasColumn('holiday_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('location_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Holiday', array(
             'local' => 'holiday_id',
             'foreign' => 'id'));
    }
}