<?php

/**
 * OldLeaveTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OldLeaveTypeTable extends PluginOldLeaveTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OldLeaveTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OldLeaveType');
    }
}