<?php

/**
 * PluginOhrmEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOhrmEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOhrmEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOhrmEmail');
    }
}