<?php
// Call EmployeeTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "EmployeeTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'Employee.php';

/**
 * Test class for Employee.
 * Generated by PHPUnit_Util_Skeleton on 2008-04-01 at 21:56:48.
 */
class EmployeeTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("EmployeeTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }


    /**
     * test method for search() 
     */
    public function testSearch() {
        // No matches
        // Search with one employee
        // Search with no employees
    }
}

// Call EmployeeTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "EmployeeTest::main") {
    EmployeeTest::main();
}
?>
