<?php
// Call EmployeeSearchTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "EmployeeSearchTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'EmployeeSearch.php';

/**
 * Test class for EmployeeSearch.
 * Generated by PHPUnit_Util_Skeleton on 2008-04-01 at 21:11:27.
 */
class EmployeeSearchTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("EmployeeSearchTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * Test method for constructor
     */
    public function testConstructor() {
        
        require_once ROOT_PATH . '/language/default/lang_default_full.php';
                
        $employee = new Employee();
        
        $empSearch = new EmployeeSearch();
        $fields = $empSearch->getSearchFields();
        $displayFields = $empSearch->getDisplayFields();
        
        // validate search fields
        foreach ($fields as $field) {
            $this->assertTrue($field instanceof SearchField);

            // Verify the field is valid
            $this->assertTrue($this->_getterExists($employee, $field->getFieldName()));
            
            // verify display language variables are set
            $displayVar = $field->getDisplayNameVar();
            $this->assertTrue(isset($$displayVar));
        }
        
        // validate display fields
        foreach ($displayFields as $field) {
            $this->assertTrue($field instanceof DisplayField);
        
            // Verify the field is valid
            $this->assertTrue($this->_getterExists($employee, $field->getFieldName()));
                
            // verify display language variables are set
            $displayVar = $field->getDisplayNameVar();
            $this->assertTrue(isset($$displayVar));
        }                
    }
    
    /**
     * Check if getter method exists for given property
     */
    private function _getterExists($object, $property) {
        $method = 'get' . ucfirst($property);
        return method_exists($object, $method);
    }
}

// Call EmployeeSearchTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "EmployeeSearchTest::main") {
    EmployeeSearchTest::main();
}
?>
