<?php

/**
 * PluginLeavePeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeavePeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeavePeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeavePeriod');
    }
}