<?php

/**
 * AdvancedLeaveTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvancedLeaveTypeTable extends PluginAdvancedLeaveTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvancedLeaveTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdvancedLeaveType');
    }
}