<?php

/**
 * EmployeeLeaveAccrualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeLeaveAccrualTable extends PluginEmployeeLeaveAccrualTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmployeeLeaveAccrualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmployeeLeaveAccrual');
    }
}