<?php

/**
 * HolidayLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HolidayLocationTable extends PluginHolidayLocationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HolidayLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HolidayLocation');
    }
}