<?php

/**
 * LeaveAccrualTimeScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveAccrualTimeScheduleTable extends PluginLeaveAccrualTimeScheduleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveAccrualTimeScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveAccrualTimeSchedule');
    }
}